# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='school',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
