# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190407_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(default=1, max_length=32, verbose_name='用户姓名'),
            preserve_default=False,
        ),
    ]
