# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userinfo_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='用户角色'),
        ),
    ]
