# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开班日期')),
                ('graduate_date', models.DateField(verbose_name='结业日期')),
                ('price', models.PositiveIntegerField(verbose_name='学费')),
                ('period', models.PositiveIntegerField(verbose_name='期')),
                ('memo', models.TextField(verbose_name='说明')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course', verbose_name='课程')),
                ('manage_teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_classes', to='web.UserInfo', verbose_name='班主任')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.School', verbose_name='校区')),
                ('teach_teacher', models.ManyToManyField(related_name='classes', to='web.UserInfo', verbose_name='教师')),
            ],
        ),
    ]
