# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190408_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateField(blank=True, verbose_name='结业日期'),
        ),
    ]
