# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190408_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
