# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190408_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='manage_teacher',
        ),
        migrations.AddField(
            model_name='classlist',
            name='manage_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='teach_teacher',
        ),
        migrations.AddField(
            model_name='classlist',
            name='teach_teacher',
            field=models.ManyToManyField(blank=True, related_name='each_classes', to='web.UserInfo', verbose_name='教师'),
        ),
    ]
