# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190408_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=32, unique=True, verbose_name='')),
                ('name', models.CharField(max_length=32, verbose_name='客户姓名')),
                ('status', models.IntegerField(choices=[(1, '已报名'), (2, '未报名')], default=2, help_text='报名状态', verbose_name='状态')),
                ('gender', models.IntegerField(choices=[(1, '女'), (2, '男')], default=2, verbose_name='性别')),
                ('work_state', models.IntegerField(choices=[(1, '在职'), (2, '无业')], verbose_name='工作状态')),
                ('source', models.SmallIntegerField(choices=[(1, 'qq群'), (2, '内部转介绍'), (3, '官方网站'), (4, '百度推广'), (5, '360推广'), (6, '搜狗推广'), (7, '腾讯课堂'), (8, '广点通'), (9, '高校宣讲'), (10, '渠道代理'), (11, '51cto'), (12, '智汇推'), (13, '网盟'), (14, 'DSP'), (15, 'SEO'), (16, '其它')], default=1, verbose_name='客户来源')),
                ('education', models.IntegerField(blank=True, choices=[(1, '重点大学'), (2, '普通本科'), (3, '独立院校'), (4, '民办本科'), (5, '大专'), (6, '民办专科'), (7, '高中'), (8, '其他')], null=True, verbose_name='学历')),
                ('graduation_school', models.CharField(blank=True, max_length=64, null=True, verbose_name='毕业学校')),
                ('major', models.CharField(blank=True, max_length=64, null=True, verbose_name='所学专业')),
                ('experience', models.IntegerField(choices=[(1, '在校生'), (2, '应届毕业'), (3, '半年以内'), (4, '半年至一年'), (5, '一年至三年'), (6, '三年至五年'), (7, '五年以上')], verbose_name='工作经验')),
                ('salary', models.CharField(blank=True, max_length=32, null=True, verbose_name='目前薪资')),
                ('company', models.CharField(blank=True, max_length=32, null=True, verbose_name='在职公司')),
                ('date', models.DateField(verbose_name='咨询时间')),
                ('last_consult_date', models.DateField(verbose_name='最后跟进时间')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='web.UserInfo', verbose_name='课程顾问')),
                ('course', models.ManyToManyField(to='web.Course', verbose_name='咨询课程')),
            ],
        ),
    ]
