# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='咨询时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_consult_date',
            field=models.DateField(auto_now_add=True, verbose_name='最后跟进时间'),
        ),
    ]
