# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190409_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=32, unique=True, verbose_name='联系方式'),
        ),
    ]
