# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='follow_user',
            new_name='customer_consultant',
        ),
    ]
