# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190411_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='web.ClassList', verbose_name='已报班级'),
        ),
    ]
